"""autodyne vs NumPy / SciPy on shared axes of functionality.

    python bench/compare.py            # prints a table and writes bench/RESULTS.md

Every case runs the same work on the same arrays in both libraries, checks the results agree,
and reports the best-of-5 time per call. autodyne's times include crossing into Rust and back
(DLPack import of the inputs, export of the result as a NumPy array), so they are end to end.
Single-threaded on both sides.
"""

import os

for var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(var, "1")

import pathlib
import platform
import timeit

import numpy as np
import scipy
from scipy import signal

import autodyne

rng = np.random.default_rng(0)


def best(fn, min_time=0.2):
    """Best time per call, in seconds."""
    timer = timeit.Timer(fn)
    number, _ = timer.autorange()
    number = max(1, int(number * min_time / 0.2))
    return min(timer.repeat(repeat=5, number=number)) / number


def check(a, b, tol):
    a, b = np.asarray(a), np.asarray(b)
    assert a.shape == b.shape, (a.shape, b.shape)
    np.testing.assert_allclose(a, b, rtol=tol, atol=tol)


cases = []


def case(group, name, numpy_fn, autodyne_fn, tol=1e-6):
    check(autodyne_fn(), numpy_fn(), tol)
    t_np, t_ad = best(numpy_fn), best(autodyne_fn)
    cases.append((group, name, t_np, t_ad))
    print(f"{group:<22} {name:<46} numpy {t_np * 1e6:10.1f} us   autodyne {t_ad * 1e6:10.1f} us   {t_np / t_ad:5.2f}x")


# element-wise: a * x + b (NumPy makes a temporary per operation; autodyne fuses one pass)
for dtype in (np.float32, np.float64):
    for n in (1_000, 100_000, 10_000_000):
        x = rng.standard_normal(n).astype(dtype)
        case("fused a*x+b", f"{np.dtype(dtype).name}, n={n:,}", lambda: 2.0 * x + 0.5, lambda: autodyne.axpb(x, 2.0, 0.5), 1e-5)

# strided inputs: views are read in place on both sides
m = rng.standard_normal((2_000, 2_000))
case("strided a*x+b", "transposed 2000x2000 f64", lambda: 2.0 * m.T + 0.5, lambda: autodyne.axpb(m.T, 2.0, 0.5))
case("strided a*x+b", "every other column, 2000x1000", lambda: 2.0 * m[:, ::2] + 0.5, lambda: autodyne.axpb(m[:, ::2], 2.0, 0.5))
case("strided a*x+b", "reversed rows", lambda: 2.0 * m[::-1] + 0.5, lambda: autodyne.axpb(m[::-1], 2.0, 0.5))

# reductions
for dtype in (np.float32, np.float64):
    v = rng.standard_normal(10_000_000).astype(dtype)
    case("sum", f"{np.dtype(dtype).name}, n=10,000,000", lambda: np.sum(v), lambda: autodyne.sum(v), 1e-3 if dtype == np.float32 else 1e-9)
case("sum", "axis 0 of 2000x2000 f64", lambda: m.sum(axis=0), lambda: autodyne.sum(m, axis=0), 1e-9)
case("sum", "axis 1 of 2000x2000 f64", lambda: m.sum(axis=1), lambda: autodyne.sum(m, axis=1), 1e-9)
case("sum", "transposed 2000x2000 f64, axis 1", lambda: m.T.sum(axis=1), lambda: autodyne.sum(m.T, axis=1), 1e-9)

# runtime-typed arithmetic: mixed dtypes promote (int16 matrix + float32 row -> float32)
pcm = rng.integers(-32768, 32767, (2_000, 2_000), dtype=np.int16)
row = rng.standard_normal(2_000).astype(np.float32)
case("mixed dtypes", "int16 2000x2000 + float32 row", lambda: pcm + row, lambda: autodyne.add(pcm, row), 1e-6)
a64 = rng.standard_normal((2_000, 2_000))
case("mixed dtypes", "float64 + float64, same shape", lambda: a64 + m, lambda: autodyne.add(a64, m), 0)

# small arrays: per-call overhead (dispatch, crossing the language boundary)
tiny = rng.standard_normal(64)
case("small calls", "sum of 64 f64", lambda: np.sum(tiny), lambda: autodyne.sum(tiny), 1e-12)
case("small calls", "a*x+b on 64 f64", lambda: 2.0 * tiny + 0.5, lambda: autodyne.axpb(tiny, 2.0, 0.5))

# IIR filtering (2nd-order Butterworth low-pass), contiguous and strided time axis
sos = signal.butter(2, 1_000.0, fs=48_000.0, output="sos")
audio = rng.standard_normal((16, 480_000)).astype(np.float32)
case("IIR (scipy sosfilt)", "16 x 480,000 f32, along contiguous time", lambda: signal.sosfilt(sos, audio, axis=-1),
     lambda: autodyne.lowpass(audio, 1_000.0, 48_000.0, axis=-1), 1e-3)
interleaved = np.ascontiguousarray(audio.T)
case("IIR (scipy sosfilt)", "480,000 x 16 f32, along strided time", lambda: signal.sosfilt(sos, interleaved, axis=0),
     lambda: autodyne.lowpass(interleaved, 1_000.0, 48_000.0, axis=0), 1e-3)

# FFT
frames = rng.standard_normal((256, 4_096))
case("FFT (numpy.fft)", "rfft, 256 x 4096 f64", lambda: np.fft.rfft(frames), lambda: autodyne.rfft(frames), 1e-8)
case("FFT (numpy.fft)", "rfft, 4096 x 64 f64", lambda: np.fft.rfft(frames.reshape(-1, 64)), lambda: autodyne.rfft(frames.reshape(-1, 64)), 1e-8)

out = pathlib.Path(__file__).with_name("RESULTS.md")
lines = [
    "# autodyne vs NumPy / SciPy",
    "",
    f"Generated by `bench/compare.py`: best of 5, single-threaded, {platform.processor() or platform.machine()},",
    f"Python {platform.python_version()}, NumPy {np.__version__}, SciPy {scipy.__version__}. autodyne times are end to end",
    "(inputs cross into Rust through DLPack, results come back as NumPy arrays). Speedup > 1 means autodyne is faster.",
    "",
    "| Axis | Case | NumPy / SciPy | autodyne | Speedup |",
    "|---|---|---:|---:|---:|",
]
for group, name, t_np, t_ad in cases:
    lines.append(f"| {group} | {name} | {t_np * 1e6:,.1f} µs | {t_ad * 1e6:,.1f} µs | {t_np / t_ad:.2f}x |")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"\nwrote {out}")
